const dummyData = [
    {
      finding: "Open port detected",
      severity: "High",
      workflowStatus: "New",
      region: "us-east-1",
      accountId: "123456789012",
      product: "Amazon EC2",
      resource: "i-0abcd1234efgh5678",
      complianceStatus: "Non-Compliant",
      updatedAt: "2025-04-17",
    },
    {
      finding: "IAM policy too permissive",
      severity: "Medium",
      workflowStatus: "InProgress",
      region: "us-west-2",
      accountId: "234567890123",
      product: "IAM",
      resource: "policy/AllowAll",
      complianceStatus: "Compliant",
      updatedAt: "2025-04-15",
    },
    {
      finding: "Outdated SSL certificate",
      severity: "Low",
      workflowStatus: "Resolved",
      region: "eu-central-1",
      accountId: "345678901234",
      product: "Amazon CloudFront",
      resource: "dist/abc123",
      complianceStatus: "Non-Compliant",
      updatedAt: "2025-04-16",
    },
    {
      finding: "Unencrypted S3 bucket",
      severity: "High",
      workflowStatus: "New",
      region: "ap-south-1",
      accountId: "456789012345",
      product: "S3",
      resource: "bucket-name",
      complianceStatus: "Non-Compliant",
      updatedAt: "2025-04-14",
    },
    // repeat to show scroll
    {
      finding: "Open port detected",
      severity: "High",
      workflowStatus: "New",
      region: "us-east-1",
      accountId: "123456789012",
      product: "Amazon EC2",
      resource: "i-0abcd1234efgh5678",
      complianceStatus: "Non-Compliant",
      updatedAt: "2025-04-17",
    },
    {
      finding: "IAM policy too permissive",
      severity: "Medium",
      workflowStatus: "InProgress",
      region: "us-west-2",
      accountId: "234567890123",
      product: "IAM",
      resource: "policy/AllowAll",
      complianceStatus: "Compliant",
      updatedAt: "2025-04-15",
    },
    {
      finding: "Outdated SSL certificate",
      severity: "Low",
      workflowStatus: "Resolved",
      region: "eu-central-1",
      accountId: "345678901234",
      product: "Amazon CloudFront",
      resource: "dist/abc123",
      complianceStatus: "Non-Compliant",
      updatedAt: "2025-04-16",
    },
    {
      finding: "Unencrypted S3 bucket",
      severity: "High",
      workflowStatus: "New",
      region: "ap-south-1",
      accountId: "456789012345",
      product: "S3",
      resource: "bucket-name",
      complianceStatus: "Non-Compliant",
      updatedAt: "2025-04-14",
    },
  ];

export default dummyData